{
  "message": "Welcome to Thunder Client",
  "about": "Lightweight Rest API Client for VSCode",
  "createdBy": "Ranga Vadhineni",
  "launched": 2021,
  "features": {
    "git": "Save data to Git Workspace",
    "themes": "Supports VSCode Themes",
    "data": "Collections & Environment Variables",
    "testing": "Scriptless Testing",
    "local": "Local Storage & Works Offline"
  },
  "supports": {
    "graphql": true,
    "codeSnippet": true,
    "requestChaining": true,
    "scripting": true
  }
}
